runtime: php55
api_version: 1

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg|js|xsl|css))$
  static_files: \1
  upload: .+\.(gif|png|jpg|js|xsl|css)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
